### ISSUE TITLE
Tried to use your step

### ISSUE THREAD

**Issue by appfabtech** [manuelgon47/bitrise-step-fabric-crashlytics-deployer#2]
Hi, first of all thanks for the step. I really would need it.
I tried it and I got the following error trying to run it in a workflow after creating the android artifacts.
Any idea?
Paolo

+ java -jar ./crashlytics/crashlytics-devtools.jar -apiKey xxxx -apiSecret xxxx -uploadDist /bitrise/deploy/app-develop-debug.apk -androidRes /bitrise/src/app/src/main -androidManifest /bitrise/src/app/src/main/AndroidManifest.xml -betaDistributionNotifications true -betaDistributionGroupAliases testappfab
 WARN - Crashlytics halted compilation because it can't extract Crashlytics build info from the APK: /bitrise/deploy/app-develop-debug.apk
Exception in thread "main" com.crashlytics.tools.android.exception.PluginException: Distribution upload failed.
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:667)
	at com.crashlytics.tools.android.DeveloperTools.processArgsInternal(DeveloperTools.java:348)
	at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:273)
Caused by: com.crashlytics.tools.android.exception.DistributionException: Crashlytics halted compilation because it can't extract Crashlytics build info from the APK: /bitrise/deploy/app-develop-debug.apk
	at com.crashlytics.tools.android.DistributionTasks.uploadDistribution(DistributionTasks.java:64)
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:665)
	... 2 more

**Comment by manuelgon47** [comment]
Hi @pcecchetti The trace is saying that the apk that you are trying to upload doesn't include the Fabric sdk.

This step is to upload the apk to Crashlytics, but you need to install the sdk following the Fabric instructions.
https://fabric.io/kits/android/crashlytics/install

If you need help, contact me again.

**Comment by pcecchetti** [comment]
Hi @manuelgon47 and thanks. Yes my developer didn't follow the correct instructions to install Crashlytics. Now he did and it works. Thanks!
One question: you select the apk to send to Crashlytics by $BITRISE_APK_PATH.
But if your gradle runner returns multiple flawers, for example
- /bitrise/deploy/xxx-develop-release.apk
- /bitrise/deploy/xxx-production-release.apk
Is it possible to use BITRISE_APK_PATH_LIST to send all of them to Crashlytics? 
Thanks!

**Comment by appfabtech** [comment]
Hi @manuelgon47 and thanks. Yes my developer didn't follow the correct instructions to install Crashlytics. Now he did and it works. Thanks!
One question: you select the apk to send to Crashlytics by $BITRISE_APK_PATH.
But if your gradle runner returns multiple flawers, for example

    /bitrise/deploy/xxx-develop-release.apk
    /bitrise/deploy/xxx-production-release.apk
    Is it possible to use BITRISE_APK_PATH_LIST to send all of them to Crashlytics?
    Thanks!

**Comment by manuelgon47** [comment]
I never tried to upload more than one apk, but I will investiga if it's possible to do. And upload the step.
Anyway you can modify the param `fabric_apk_path` in your `bitrise.yml`
```    
    - git::https://github.com/manuelgon47/bitrise-step-fabric-crashlytics-deployer@master:
       title: deploy fabric
       inputs:
       - fabric_api_key: "Your api key"
       - fabric_build_secret: "your secret"
       - fabric_apk_path: "BITRISE_APK_PATH_LIST"
       - fabric_android_res: "$BITRISE_SOURCE_DIR/app/src/main"
       - fabric_android_manifest: "$BITRISE_SOURCE_DIR/app/src/main/AndroidManifest.xml"
       - fabric_beta_distribution_notification: "Yes"
       - fabric_beta_distribution_list: "testGroup"
```

I'll notice you about to upload more than one apk as soon as I tried it.
